default: &default
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  username: root
  password:
  database: configurable_email_test
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
